services:
  inventoryservice:
    image: inventoryservice
    build:
      context: .
      dockerfile: InventoryService.Api/Dockerfile
    ports:
      - "${INVENTORYSERVICE_PORT}:${INVENTORYSERVICE_PORT}"
      - "${INVENTORYSERVICE_PORTALT}:${INVENTORYSERVICE_PORTALT}"
    env_file:
      - ../.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - inventoryservice-data:/app/Data
    networks:
      - shared-network

volumes:
  inventoryservice-data:
  store-mq-data:

networks:
  shared-network:
    external: true
